// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26JNuoyNzhDRTmV3Y4BCYy1DPHdkYw5k',
    appId: '1:749349449042:web:81e5a8f8219f1c25479e8b',
    messagingSenderId: '749349449042',
    projectId: 'notes-3bb67',
    authDomain: 'notes-3bb67.firebaseapp.com',
    storageBucket: 'notes-3bb67.firebasestorage.app',
    measurementId: 'G-WS7YC02CE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY4fr8tLwReohNnbXBBWsDyBOUywov8Vs',
    appId: '1:749349449042:android:e6a62646eb2f023a479e8b',
    messagingSenderId: '749349449042',
    projectId: 'notes-3bb67',
    storageBucket: 'notes-3bb67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACRLVzD9pVYcg_Ifxx_RdEbgE8RsjSii0',
    appId: '1:749349449042:ios:9d431c0002d2b3fa479e8b',
    messagingSenderId: '749349449042',
    projectId: 'notes-3bb67',
    storageBucket: 'notes-3bb67.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
